### Get config
GET {{matreshka-api}}/api/config/{{example_service_name}}

### Get config not existing config
GET {{matreshka-api}}/api/config/unknown

### Get config by nodes
GET {{matreshka-api}}/api/config/nodes/{{example_service_name}}


### List configs
POST {{matreshka-api}}/api/config/list
Content-Type: application/json

{}
