### Create config
POST {{matreshka-api}}/config
Content-Type: application/json

{
  "config": {
    "app_config": {
      "name":  "test_service",
      "version": "v0.0.1",
      "startup_duration_sec":  10
    },
    "resources": [
      {
      }
    ],
    "api": [],
    "environment": {}
  }
}

### Get raw config
GET {{matreshka-api}}/config/raw/test_service

### Get config
GET {{matreshka-api}}/config/test_service


### List configs
POST {{matreshka-api}}/config/list
Content-Type: application/json

{

}