### Create config
POST {{matreshka-api}}/config
Content-Type: application/json

{
  "config": {
    "app_config": {
      "name": "test_service",
      "version": "v0.0.1",
      "startup_duration_sec": 10
    },
    "resources": [
      {
        "conn": {
          "connectionString": "i dunno"
        },
        "name": "unknown",
        "resourceType": "UnknownResourceType",
        "resourceConfig": {
          "unknown": {
            "environment": {
              "one": "two"
            }
          }
        }
      },
      {
        "conn": {
          "connectionString": "psql -H localhost -p 5432 -u postgres -d postgres"
        },
        "name": "postgres",
        "resourceType": "PostgresResourceType",
        "resourceConfig": {
          "postgres": {
            "host": "localhost",
            "port": 5432,
            "db_name": "postgres",
            "user_name": "postgres",
            "pwd": "postgres_pwd"
          }
        }
      },
      {
        "conn": {
          "connectionString": "redis-cli -h localhost -p 5001"
        },
        "name": "redis",
        "resourceType": "RedisResourceType",
        "resourceConfig": {
          "redis": {
            "host": "localhost",
            "port": 5001,
            "user": "redis",
            "pwd": "pwd",
            "db": 1
          }
        }
      },
      {
        "conn": {
          "connectionString": "sqlite /app/data"
        },
        "name": "sqlite",
        "resourceType": "SqliteResourceType",
        "resourceConfig": {
          "sqlite": {
            "path": "/app/data"
          }
        }
      },
      {
        "conn": {},
        "name": "grpc",
        "resourceType": "GrpcResourceType",
        "resourceConfig": {
          "grpc": {
            "connectionString": "localhost:50055",
            "module": "github.com/verv/matreshka@latest"
          }
        }
      },
      {
        "conn": {},
        "name": "telegram",
        "resourceType": "TelegramResourceType",
        "resourceConfig": {
          "telegram": {
            "apiKey": "contractanalysismatt"
          }
        }
      }
    ],
    "servers": [
      {
        "type": "UnknownServerType",
        "swaggerLink": "localhost:50056/docs",
        "makoshName": "test_service",
        "config": {
          "unknown": {
            "environment": {
              "a": "b"
            }
          }
        }
      },
      {
        "type": "GrpcServerType",
        "swaggerLink": "localhost:50056/grpc",
        "makoshName": "test_service",
        "config": {
          "grpc": {
            "port": 50056
          }
        }
      },
      {
        "type": "RestServerType",
        "swaggerLink": "localhost:50056/rest",
        "makoshName": "test_service",
        "config": {
          "grpc": {
            "port": 50056
          }
        }
      }
    ],
    "environment": {
      "A": "boba",
      "bo": "aba"
    }
  }
}

### Get raw config
GET {{matreshka-api}}/config/raw/test_service

### Get config
GET {{matreshka-api}}/config/test_service


### List configs
POST {{matreshka-api}}/config/list
Content-Type: application/json

{

}