// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"net/http"

	"google.golang.org/grpc"

	"github.com/godverv/matreshka-be/internal/service"
	v1 "github.com/godverv/matreshka-be/internal/service/servicev1"
	"github.com/godverv/matreshka-be/internal/service/user_errors"
	"github.com/godverv/matreshka-be/internal/storage"
	"github.com/godverv/matreshka-be/internal/storage/sqlite"
	"github.com/godverv/matreshka-be/internal/storage/tx_manager"
	"github.com/godverv/matreshka-be/internal/transport/grpc_impl"
	"github.com/godverv/matreshka-be/internal/transport/web_client"
)

type Custom struct {
	DataProvider storage.Data

	Srv service.ConfigService

	GrpcImpl  *grpc_impl.Impl
	WebClient http.Handler
}

func (c *Custom) Init(a *App) (err error) {
	// Repository, Service logic, transport registration happens here
	c.DataProvider = sqlite.New(a.Sqlite)

	txManager := tx_manager.New(a.Sqlite)

	c.Srv = v1.New(c.DataProvider, txManager)

	c.GrpcImpl = grpc_impl.NewServer(a.Cfg, c.Srv, c.DataProvider)

	a.Server.AddImplementation(c.GrpcImpl,
		grpc.UnaryInterceptor(user_errors.ErrorInterceptor()))

	c.WebClient = web_client.NewServer()
	a.Server.AddHttpHandler("/", c.WebClient)
	return nil
}
