// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"github.com/godverv/matreshka-be/internal/service"
)

type Custom struct {
	Srv service.ConfigService
}

func (c Custom) Init(a *App) error {
	// Repository, Service logic, transport registration happens here
	return nil
}
