// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	errors "github.com/Red-Sock/trace-errors"
	"github.com/godverv/matreshka-be/internal/transport"
)

func (a *App) InitServers() (err error) {
	a.Server, err = transport.NewServerManager(a.Ctx, ":80")
	if err != nil {
		return errors.Wrap(err, "error during server initialization on port: 80")
	}

	return nil
}
