// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: grpc/matreshka-be_api.proto

package matreshka_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_Resource_Type int32

const (
	Config_Resource_unknown  Config_Resource_Type = 0
	Config_Resource_postgres Config_Resource_Type = 1
	Config_Resource_redis    Config_Resource_Type = 2
	Config_Resource_grpc     Config_Resource_Type = 3
	Config_Resource_telegram Config_Resource_Type = 4
)

// Enum value maps for Config_Resource_Type.
var (
	Config_Resource_Type_name = map[int32]string{
		0: "unknown",
		1: "postgres",
		2: "redis",
		3: "grpc",
		4: "telegram",
	}
	Config_Resource_Type_value = map[string]int32{
		"unknown":  0,
		"postgres": 1,
		"redis":    2,
		"grpc":     3,
		"telegram": 4,
	}
)

func (x Config_Resource_Type) Enum() *Config_Resource_Type {
	p := new(Config_Resource_Type)
	*p = x
	return p
}

func (x Config_Resource_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Resource_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_matreshka_be_api_proto_enumTypes[0].Descriptor()
}

func (Config_Resource_Type) Type() protoreflect.EnumType {
	return &file_grpc_matreshka_be_api_proto_enumTypes[0]
}

func (x Config_Resource_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Resource_Type.Descriptor instead.
func (Config_Resource_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 1, 0}
}

type Config_Api_Type int32

const (
	Config_Api_unknown Config_Api_Type = 0
	Config_Api_grpc    Config_Api_Type = 1
	Config_Api_rest    Config_Api_Type = 2
)

// Enum value maps for Config_Api_Type.
var (
	Config_Api_Type_name = map[int32]string{
		0: "unknown",
		1: "grpc",
		2: "rest",
	}
	Config_Api_Type_value = map[string]int32{
		"unknown": 0,
		"grpc":    1,
		"rest":    2,
	}
)

func (x Config_Api_Type) Enum() *Config_Api_Type {
	p := new(Config_Api_Type)
	*p = x
	return p
}

func (x Config_Api_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Api_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_matreshka_be_api_proto_enumTypes[1].Descriptor()
}

func (Config_Api_Type) Type() protoreflect.EnumType {
	return &file_grpc_matreshka_be_api_proto_enumTypes[1]
}

func (x Config_Api_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Api_Type.Descriptor instead.
func (Config_Api_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 2, 0}
}

type ApiVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiVersion) Reset() {
	*x = ApiVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion) ProtoMessage() {}

func (x *ApiVersion) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion.ProtoReflect.Descriptor instead.
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{0}
}

type UpdateServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateServiceConfig) Reset() {
	*x = UpdateServiceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceConfig) ProtoMessage() {}

func (x *UpdateServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceConfig.ProtoReflect.Descriptor instead.
func (*UpdateServiceConfig) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppConfig   *Config_AppConfig     `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Resources   []*Config_Resource    `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Api         []*Config_Api         `protobuf:"bytes,3,rep,name=api,proto3" json:"api,omitempty"`
	Environment []*Config_Environment `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2}
}

func (x *Config) GetAppConfig() *Config_AppConfig {
	if x != nil {
		return x.AppConfig
	}
	return nil
}

func (x *Config) GetResources() []*Config_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Config) GetApi() []*Config_Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Config) GetEnvironment() []*Config_Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type GetConfigRaw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConfigRaw) Reset() {
	*x = GetConfigRaw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRaw) ProtoMessage() {}

func (x *GetConfigRaw) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRaw.ProtoReflect.Descriptor instead.
func (*GetConfigRaw) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{3}
}

type GetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConfig) Reset() {
	*x = GetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig) ProtoMessage() {}

func (x *GetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig.ProtoReflect.Descriptor instead.
func (*GetConfig) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{4}
}

type PatchConfigEnv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchConfigEnv) Reset() {
	*x = PatchConfigEnv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchConfigEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfigEnv) ProtoMessage() {}

func (x *PatchConfigEnv) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfigEnv.ProtoReflect.Descriptor instead.
func (*PatchConfigEnv) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{5}
}

type ApiVersion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiVersion_Request) Reset() {
	*x = ApiVersion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion_Request) ProtoMessage() {}

func (x *ApiVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion_Request.ProtoReflect.Descriptor instead.
func (*ApiVersion_Request) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{0, 0}
}

type ApiVersion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ApiVersion_Response) Reset() {
	*x = ApiVersion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion_Response) ProtoMessage() {}

func (x *ApiVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion_Response.ProtoReflect.Descriptor instead.
func (*ApiVersion_Response) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ApiVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateServiceConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateServiceConfig_Request) Reset() {
	*x = UpdateServiceConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceConfig_Request) ProtoMessage() {}

func (x *UpdateServiceConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceConfig_Request.ProtoReflect.Descriptor instead.
func (*UpdateServiceConfig_Request) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateServiceConfig_Request) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateServiceConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *UpdateServiceConfig_Response) Reset() {
	*x = UpdateServiceConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceConfig_Response) ProtoMessage() {}

func (x *UpdateServiceConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceConfig_Response.ProtoReflect.Descriptor instead.
func (*UpdateServiceConfig_Response) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UpdateServiceConfig_Response) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Config_AppConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// e.g "10s"
	StartupDuration string `protobuf:"bytes,3,opt,name=startup_duration,json=startupDuration,proto3" json:"startup_duration,omitempty"`
}

func (x *Config_AppConfig) Reset() {
	*x = Config_AppConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_AppConfig) ProtoMessage() {}

func (x *Config_AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_AppConfig.ProtoReflect.Descriptor instead.
func (*Config_AppConfig) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Config_AppConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_AppConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config_AppConfig) GetStartupDuration() string {
	if x != nil {
		return x.StartupDuration
	}
	return ""
}

type Config_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceType Config_Resource_Type `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=matreshka_be_api.Config_Resource_Type" json:"resource_type,omitempty"`
	// link to resource configuration if available
	SecretsLink string `protobuf:"bytes,2,opt,name=secrets_link,json=secretsLink,proto3" json:"secrets_link,omitempty"`
}

func (x *Config_Resource) Reset() {
	*x = Config_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Resource) ProtoMessage() {}

func (x *Config_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Resource.ProtoReflect.Descriptor instead.
func (*Config_Resource) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Config_Resource) GetResourceType() Config_Resource_Type {
	if x != nil {
		return x.ResourceType
	}
	return Config_Resource_unknown
}

func (x *Config_Resource) GetSecretsLink() string {
	if x != nil {
		return x.SecretsLink
	}
	return ""
}

type Config_Api struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiType     Config_Api_Type `protobuf:"varint,1,opt,name=api_type,json=apiType,proto3,enum=matreshka_be_api.Config_Api_Type" json:"api_type,omitempty"`
	SwaggerLink string          `protobuf:"bytes,2,opt,name=swagger_link,json=swaggerLink,proto3" json:"swagger_link,omitempty"`
	MakoshName  string          `protobuf:"bytes,3,opt,name=makosh_name,json=makoshName,proto3" json:"makosh_name,omitempty"`
}

func (x *Config_Api) Reset() {
	*x = Config_Api{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Api) ProtoMessage() {}

func (x *Config_Api) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Api.ProtoReflect.Descriptor instead.
func (*Config_Api) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Config_Api) GetApiType() Config_Api_Type {
	if x != nil {
		return x.ApiType
	}
	return Config_Api_unknown
}

func (x *Config_Api) GetSwaggerLink() string {
	if x != nil {
		return x.SwaggerLink
	}
	return ""
}

func (x *Config_Api) GetMakoshName() string {
	if x != nil {
		return x.MakoshName
	}
	return ""
}

type Config_Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Config_Environment) Reset() {
	*x = Config_Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Environment) ProtoMessage() {}

func (x *Config_Environment) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Environment.ProtoReflect.Descriptor instead.
func (*Config_Environment) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Config_Environment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Config_Environment) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetConfigRaw_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *GetConfigRaw_Request) Reset() {
	*x = GetConfigRaw_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigRaw_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRaw_Request) ProtoMessage() {}

func (x *GetConfigRaw_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRaw_Request.ProtoReflect.Descriptor instead.
func (*GetConfigRaw_Request) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetConfigRaw_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetConfigRaw_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetConfigRaw_Response) Reset() {
	*x = GetConfigRaw_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigRaw_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRaw_Response) ProtoMessage() {}

func (x *GetConfigRaw_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRaw_Response.ProtoReflect.Descriptor instead.
func (*GetConfigRaw_Response) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetConfigRaw_Response) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *GetConfig_Request) Reset() {
	*x = GetConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig_Request) ProtoMessage() {}

func (x *GetConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig_Request.ProtoReflect.Descriptor instead.
func (*GetConfig_Request) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetConfig_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetConfig_Response) Reset() {
	*x = GetConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfig_Response) ProtoMessage() {}

func (x *GetConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfig_Response.ProtoReflect.Descriptor instead.
func (*GetConfig_Response) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetConfig_Response) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type PatchConfigEnv_Patch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PatchConfigEnv_Patch) Reset() {
	*x = PatchConfigEnv_Patch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchConfigEnv_Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfigEnv_Patch) ProtoMessage() {}

func (x *PatchConfigEnv_Patch) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfigEnv_Patch.ProtoReflect.Descriptor instead.
func (*PatchConfigEnv_Patch) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PatchConfigEnv_Patch) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *PatchConfigEnv_Patch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PatchConfigEnv_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string                  `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Patches     []*PatchConfigEnv_Patch `protobuf:"bytes,2,rep,name=patches,proto3" json:"patches,omitempty"`
}

func (x *PatchConfigEnv_Request) Reset() {
	*x = PatchConfigEnv_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchConfigEnv_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfigEnv_Request) ProtoMessage() {}

func (x *PatchConfigEnv_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfigEnv_Request.ProtoReflect.Descriptor instead.
func (*PatchConfigEnv_Request) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *PatchConfigEnv_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PatchConfigEnv_Request) GetPatches() []*PatchConfigEnv_Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type PatchConfigEnv_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchConfigEnv_Response) Reset() {
	*x = PatchConfigEnv_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_matreshka_be_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchConfigEnv_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConfigEnv_Response) ProtoMessage() {}

func (x *PatchConfigEnv_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matreshka_be_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConfigEnv_Response.ProtoReflect.Descriptor instead.
func (*PatchConfigEnv_Response) Descriptor() ([]byte, []int) {
	return file_grpc_matreshka_be_api_proto_rawDescGZIP(), []int{5, 2}
}

var File_grpc_matreshka_be_api_proto protoreflect.FileDescriptor

var file_grpc_matreshka_be_api_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61,
	0x2d, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d,
	0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a,
	0x0a, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x72, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x22, 0x97, 0x06, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41, 0x0a, 0x0a, 0x61,
	0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x09, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3f,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d,
	0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12,
	0x46, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61,
	0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x64, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x5f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x75, 0x70, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xc0, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x44, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x10, 0x04,
	0x1a, 0xb0, 0x01, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x12, 0x3c, 0x0a, 0x08, 0x61, 0x70, 0x69, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x74,
	0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x61,
	0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x77,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x6b,
	0x6f, 0x73, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x6b, 0x6f, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x65, 0x73,
	0x74, 0x10, 0x02, 0x1a, 0x35, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x60, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x61, 0x77, 0x1a, 0x2c, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x77, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f,
	0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x76, 0x1a, 0x3c, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x6e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b,
	0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x76, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x70,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x8e, 0x05, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61,
	0x42, 0x65, 0x41, 0x50, 0x49, 0x12, 0x6b, 0x0a, 0x0a, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f,
	0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x74, 0x72,
	0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x83, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x61, 0x77, 0x12, 0x26, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f,
	0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x61, 0x77, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x61,
	0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x61, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x72, 0x61, 0x77, 0x2f, 0x7b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x76, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b,
	0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x74,
	0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x7b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d,
	0x12, 0x8f, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65,
	0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73,
	0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x3a,
	0x01, 0x2a, 0x22, 0x0e, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x7f, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x45, 0x6e, 0x76, 0x12, 0x28, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61,
	0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x45, 0x6e, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b, 0x61, 0x5f, 0x62, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x76,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x3a, 0x01, 0x2a, 0x32, 0x0d, 0x2f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x6d, 0x61, 0x74, 0x72, 0x65, 0x73, 0x68, 0x6b,
	0x61, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_matreshka_be_api_proto_rawDescOnce sync.Once
	file_grpc_matreshka_be_api_proto_rawDescData = file_grpc_matreshka_be_api_proto_rawDesc
)

func file_grpc_matreshka_be_api_proto_rawDescGZIP() []byte {
	file_grpc_matreshka_be_api_proto_rawDescOnce.Do(func() {
		file_grpc_matreshka_be_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_matreshka_be_api_proto_rawDescData)
	})
	return file_grpc_matreshka_be_api_proto_rawDescData
}

var file_grpc_matreshka_be_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_matreshka_be_api_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_grpc_matreshka_be_api_proto_goTypes = []interface{}{
	(Config_Resource_Type)(0),            // 0: matreshka_be_api.Config.Resource.Type
	(Config_Api_Type)(0),                 // 1: matreshka_be_api.Config.Api.Type
	(*ApiVersion)(nil),                   // 2: matreshka_be_api.ApiVersion
	(*UpdateServiceConfig)(nil),          // 3: matreshka_be_api.UpdateServiceConfig
	(*Config)(nil),                       // 4: matreshka_be_api.Config
	(*GetConfigRaw)(nil),                 // 5: matreshka_be_api.GetConfigRaw
	(*GetConfig)(nil),                    // 6: matreshka_be_api.GetConfig
	(*PatchConfigEnv)(nil),               // 7: matreshka_be_api.PatchConfigEnv
	(*ApiVersion_Request)(nil),           // 8: matreshka_be_api.ApiVersion.Request
	(*ApiVersion_Response)(nil),          // 9: matreshka_be_api.ApiVersion.Response
	(*UpdateServiceConfig_Request)(nil),  // 10: matreshka_be_api.UpdateServiceConfig.Request
	(*UpdateServiceConfig_Response)(nil), // 11: matreshka_be_api.UpdateServiceConfig.Response
	(*Config_AppConfig)(nil),             // 12: matreshka_be_api.Config.AppConfig
	(*Config_Resource)(nil),              // 13: matreshka_be_api.Config.Resource
	(*Config_Api)(nil),                   // 14: matreshka_be_api.Config.Api
	(*Config_Environment)(nil),           // 15: matreshka_be_api.Config.Environment
	(*GetConfigRaw_Request)(nil),         // 16: matreshka_be_api.GetConfigRaw.Request
	(*GetConfigRaw_Response)(nil),        // 17: matreshka_be_api.GetConfigRaw.Response
	(*GetConfig_Request)(nil),            // 18: matreshka_be_api.GetConfig.Request
	(*GetConfig_Response)(nil),           // 19: matreshka_be_api.GetConfig.Response
	(*PatchConfigEnv_Patch)(nil),         // 20: matreshka_be_api.PatchConfigEnv.Patch
	(*PatchConfigEnv_Request)(nil),       // 21: matreshka_be_api.PatchConfigEnv.Request
	(*PatchConfigEnv_Response)(nil),      // 22: matreshka_be_api.PatchConfigEnv.Response
}
var file_grpc_matreshka_be_api_proto_depIdxs = []int32{
	12, // 0: matreshka_be_api.Config.app_config:type_name -> matreshka_be_api.Config.AppConfig
	13, // 1: matreshka_be_api.Config.resources:type_name -> matreshka_be_api.Config.Resource
	14, // 2: matreshka_be_api.Config.api:type_name -> matreshka_be_api.Config.Api
	15, // 3: matreshka_be_api.Config.environment:type_name -> matreshka_be_api.Config.Environment
	4,  // 4: matreshka_be_api.UpdateServiceConfig.Request.config:type_name -> matreshka_be_api.Config
	0,  // 5: matreshka_be_api.Config.Resource.resource_type:type_name -> matreshka_be_api.Config.Resource.Type
	1,  // 6: matreshka_be_api.Config.Api.api_type:type_name -> matreshka_be_api.Config.Api.Type
	4,  // 7: matreshka_be_api.GetConfig.Response.config:type_name -> matreshka_be_api.Config
	20, // 8: matreshka_be_api.PatchConfigEnv.Request.patches:type_name -> matreshka_be_api.PatchConfigEnv.Patch
	8,  // 9: matreshka_be_api.MatreshkaBeAPI.ApiVersion:input_type -> matreshka_be_api.ApiVersion.Request
	16, // 10: matreshka_be_api.MatreshkaBeAPI.GetConfigRaw:input_type -> matreshka_be_api.GetConfigRaw.Request
	18, // 11: matreshka_be_api.MatreshkaBeAPI.GetConfig:input_type -> matreshka_be_api.GetConfig.Request
	10, // 12: matreshka_be_api.MatreshkaBeAPI.UpdateServiceConfig:input_type -> matreshka_be_api.UpdateServiceConfig.Request
	21, // 13: matreshka_be_api.MatreshkaBeAPI.PatchConfigEnv:input_type -> matreshka_be_api.PatchConfigEnv.Request
	9,  // 14: matreshka_be_api.MatreshkaBeAPI.ApiVersion:output_type -> matreshka_be_api.ApiVersion.Response
	17, // 15: matreshka_be_api.MatreshkaBeAPI.GetConfigRaw:output_type -> matreshka_be_api.GetConfigRaw.Response
	19, // 16: matreshka_be_api.MatreshkaBeAPI.GetConfig:output_type -> matreshka_be_api.GetConfig.Response
	11, // 17: matreshka_be_api.MatreshkaBeAPI.UpdateServiceConfig:output_type -> matreshka_be_api.UpdateServiceConfig.Response
	22, // 18: matreshka_be_api.MatreshkaBeAPI.PatchConfigEnv:output_type -> matreshka_be_api.PatchConfigEnv.Response
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_matreshka_be_api_proto_init() }
func file_grpc_matreshka_be_api_proto_init() {
	if File_grpc_matreshka_be_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_matreshka_be_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigRaw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchConfigEnv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiVersion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiVersion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_AppConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Api); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigRaw_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigRaw_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchConfigEnv_Patch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchConfigEnv_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_matreshka_be_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchConfigEnv_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_matreshka_be_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_matreshka_be_api_proto_goTypes,
		DependencyIndexes: file_grpc_matreshka_be_api_proto_depIdxs,
		EnumInfos:         file_grpc_matreshka_be_api_proto_enumTypes,
		MessageInfos:      file_grpc_matreshka_be_api_proto_msgTypes,
	}.Build()
	File_grpc_matreshka_be_api_proto = out.File
	file_grpc_matreshka_be_api_proto_rawDesc = nil
	file_grpc_matreshka_be_api_proto_goTypes = nil
	file_grpc_matreshka_be_api_proto_depIdxs = nil
}
