/**
 * @fileoverview gRPC-Web generated client stub for matreshka_be_api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: grpc/matreshka-be_api.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as grpc_matreshka$be_api_pb from '../grpc/matreshka-be_api_pb'; // proto import: "grpc/matreshka-be_api.proto"


export class MatreshkaBeAPIClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorApiVersion = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/ApiVersion',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.ApiVersion.Request,
    grpc_matreshka$be_api_pb.ApiVersion.Response,
    (request: grpc_matreshka$be_api_pb.ApiVersion.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.ApiVersion.Response.deserializeBinary
  );

  apiVersion(
    request: grpc_matreshka$be_api_pb.ApiVersion.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.ApiVersion.Response>;

  apiVersion(
    request: grpc_matreshka$be_api_pb.ApiVersion.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.ApiVersion.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.ApiVersion.Response>;

  apiVersion(
    request: grpc_matreshka$be_api_pb.ApiVersion.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.ApiVersion.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/ApiVersion',
        request,
        metadata || {},
        this.methodDescriptorApiVersion,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/ApiVersion',
    request,
    metadata || {},
    this.methodDescriptorApiVersion);
  }

  methodDescriptorUpsertConfig = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/UpsertConfig',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.PatchConfig.Request,
    grpc_matreshka$be_api_pb.PatchConfig.Response,
    (request: grpc_matreshka$be_api_pb.PatchConfig.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.PatchConfig.Response.deserializeBinary
  );

  upsertConfig(
    request: grpc_matreshka$be_api_pb.PatchConfig.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.PatchConfig.Response>;

  upsertConfig(
    request: grpc_matreshka$be_api_pb.PatchConfig.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.PatchConfig.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.PatchConfig.Response>;

  upsertConfig(
    request: grpc_matreshka$be_api_pb.PatchConfig.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.PatchConfig.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/UpsertConfig',
        request,
        metadata || {},
        this.methodDescriptorUpsertConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/UpsertConfig',
    request,
    metadata || {},
    this.methodDescriptorUpsertConfig);
  }

  methodDescriptorGetConfig = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/GetConfig',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.GetConfig.Request,
    grpc_matreshka$be_api_pb.GetConfig.Response,
    (request: grpc_matreshka$be_api_pb.GetConfig.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.GetConfig.Response.deserializeBinary
  );

  getConfig(
    request: grpc_matreshka$be_api_pb.GetConfig.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.GetConfig.Response>;

  getConfig(
    request: grpc_matreshka$be_api_pb.GetConfig.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.GetConfig.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.GetConfig.Response>;

  getConfig(
    request: grpc_matreshka$be_api_pb.GetConfig.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.GetConfig.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/GetConfig',
        request,
        metadata || {},
        this.methodDescriptorGetConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/GetConfig',
    request,
    metadata || {},
    this.methodDescriptorGetConfig);
  }

  methodDescriptorGetConfigRaw = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/GetConfigRaw',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.GetConfigRaw.Request,
    grpc_matreshka$be_api_pb.GetConfigRaw.Response,
    (request: grpc_matreshka$be_api_pb.GetConfigRaw.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.GetConfigRaw.Response.deserializeBinary
  );

  getConfigRaw(
    request: grpc_matreshka$be_api_pb.GetConfigRaw.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.GetConfigRaw.Response>;

  getConfigRaw(
    request: grpc_matreshka$be_api_pb.GetConfigRaw.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.GetConfigRaw.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.GetConfigRaw.Response>;

  getConfigRaw(
    request: grpc_matreshka$be_api_pb.GetConfigRaw.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.GetConfigRaw.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/GetConfigRaw',
        request,
        metadata || {},
        this.methodDescriptorGetConfigRaw,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/GetConfigRaw',
    request,
    metadata || {},
    this.methodDescriptorGetConfigRaw);
  }

  methodDescriptorPatchConfigRaw = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/PatchConfigRaw',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.PatchConfigRaw.Request,
    grpc_matreshka$be_api_pb.PatchConfigRaw.Response,
    (request: grpc_matreshka$be_api_pb.PatchConfigRaw.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.PatchConfigRaw.Response.deserializeBinary
  );

  patchConfigRaw(
    request: grpc_matreshka$be_api_pb.PatchConfigRaw.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.PatchConfigRaw.Response>;

  patchConfigRaw(
    request: grpc_matreshka$be_api_pb.PatchConfigRaw.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.PatchConfigRaw.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.PatchConfigRaw.Response>;

  patchConfigRaw(
    request: grpc_matreshka$be_api_pb.PatchConfigRaw.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.PatchConfigRaw.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/PatchConfigRaw',
        request,
        metadata || {},
        this.methodDescriptorPatchConfigRaw,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/PatchConfigRaw',
    request,
    metadata || {},
    this.methodDescriptorPatchConfigRaw);
  }

  methodDescriptorListConfigs = new grpcWeb.MethodDescriptor(
    '/matreshka_be_api.MatreshkaBeAPI/ListConfigs',
    grpcWeb.MethodType.UNARY,
    grpc_matreshka$be_api_pb.ListConfigs.Request,
    grpc_matreshka$be_api_pb.ListConfigs.Response,
    (request: grpc_matreshka$be_api_pb.ListConfigs.Request) => {
      return request.serializeBinary();
    },
    grpc_matreshka$be_api_pb.ListConfigs.Response.deserializeBinary
  );

  listConfigs(
    request: grpc_matreshka$be_api_pb.ListConfigs.Request,
    metadata?: grpcWeb.Metadata | null): Promise<grpc_matreshka$be_api_pb.ListConfigs.Response>;

  listConfigs(
    request: grpc_matreshka$be_api_pb.ListConfigs.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.ListConfigs.Response) => void): grpcWeb.ClientReadableStream<grpc_matreshka$be_api_pb.ListConfigs.Response>;

  listConfigs(
    request: grpc_matreshka$be_api_pb.ListConfigs.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_matreshka$be_api_pb.ListConfigs.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/matreshka_be_api.MatreshkaBeAPI/ListConfigs',
        request,
        metadata || {},
        this.methodDescriptorListConfigs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/matreshka_be_api.MatreshkaBeAPI/ListConfigs',
    request,
    metadata || {},
    this.methodDescriptorListConfigs);
  }

}

