// Code generated by RedSock CLI. DO NOT EDIT

package grpc

import (
	"context"
	"net/http"

	"google.golang.org/grpc"

	"github.com/godverv/matreshka-be/internal/config"
	"github.com/godverv/matreshka-be/internal/data"
	"github.com/godverv/matreshka-be/internal/service"
	"github.com/godverv/matreshka-be/internal/transport/grpc/gateway"
	"github.com/godverv/matreshka-be/pkg/matreshka_api"
)

type Server struct {
	App
}

func NewServer(
	cfg config.Config,
	service service.ConfigService,
	storage data.Data,
) func(l *grpc.Server) http.Handler {

	return func(srv *grpc.Server) (gw http.Handler) {

		s := &Server{
			App: App{
				version: cfg.GetAppInfo().Version,
				service: service,
				storage: storage,
			},
		}

		matreshka_api.RegisterMatreshkaBeAPIServer(srv, s)

		return gateway.NewGrpcGateway(context.Background(), &s.App)
	}
}
